name: Lerna release
on:
  push:
    branches:
      - main
      - develop
      - develop*
permissions:
  contents: read #  for checkout
jobs:
  release:
    permissions:
      contents: write #  to be able to publish a GitHub release
      issues: write #  to be able to comment on released issues
      pull-requests: write #  to be able to comment on released pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Install Node
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.6
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install --no-frozen-lockfile && pnpm build
        name: Install & Build

      - name: Write NPM_TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Version & Publish
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid develop --yes
          elif [ "${{ github.ref }}" = "refs/heads/develop-pedago" ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid develop-pedago --yes
          elif [ "${{ github.ref }}" = "refs/heads/develop-b2school" ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid develop-b2school --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --create-release github --yes
          fi

          npx lerna publish from-git --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
